Added Screen Wrapper
nishmeht7/myrror-app pull request #5
Opened 2020-09-26 09:32 UTC by erictlieu

Wrappers for Text and Buttons

Below is a screenshot with test changes to the styles of the wrappers

<img width="364" alt="Screen Shot 2020-09-26 at 2 10 21 AM" src="https://user-images.githubusercontent.com/10472505/94337572-51c5f700-ffa0-11ea-8ffd-20a670baa0a2.png">

2020-09-27 06:01 UTC, nishmeht7 requested changes

2020-09-27 06:01 UTC, nishmeht7 commented on src/components/RNText.tsx
> +const RNText: FunctionComponent<RNTextProps> = ({ children, textType, style }) => {
Also you can name this component Text - since the goal is to not use the default Text component from react-native

2020-09-27 06:01 UTC, nishmeht7 commented on src/components/RNButton.tsx
> +const RNButton: FunctionComponent<RNButtonProps> = ({
You can just name this Button

2020-09-28 15:30 UTC, mkarazin commented on src/components/RNButton.tsx
> +  switch (buttonType) {
Good thinking Nishant. Would be good to get this component to have props for these two items and allow overrides.

For variants/styling, the coding style I frequently see is something like this:
```
const Button = ({ style, success }) => (
    <TouchableOpacity
        style={[
            styles.buttonContainer,
            success && styles.success,
            style,
        ]}
....
```

Then you can call it like: `<Button success />` or `<Button style={styles.customButtonStyling} />` or just plain `<Button />` and the styles will all be applied correctly.

2020-09-29 06:18 UTC, erictlieu commented
RNText cannot be renamed as Text since it uses Text inside the component.

2020-09-29 06:20 UTC, erictlieu commented on src/components/RNText.tsx
> +const RNText: FunctionComponent<RNTextProps> = ({ children, textType, style }) => {
I'm not able to rename it to Text since RNText uses Text in the component

2020-09-29 06:22 UTC, erictlieu commented on src/components/RNText.tsx
> +    fontSize: 12,
I removed this since we can pass size as a prop

2020-10-01 22:15 UTC, nishmeht7 approved these changes

2020-10-01 22:29 UTC, merged